/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo.Viaje;

import Modulo.Principal.Principal;

/**
 *
 * @author SevenPok
 */
public class MenuViaje extends javax.swing.JFrame {

    import Entidad.
    *;
    import Estructura.TablaHash.TablaHash ;

    /**
     *
     * @author Co
     */
    public class MenuViaje extends javax.swing.JFrame {

        TablaHash tabla = TablaHash.getInstance();

        /**
         * Creates new form MenuViaje
         */
        public MenuViaje() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Viajes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setText("Crear Viaje");

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton5.setText("Mostrar Estructura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal ventana = new Principal();
        ventana.show(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

        jLabel1  = new javax.swing.JLabel();
        txtorigen  = new javax.swing.JTextField();
        jLabel2  = new javax.swing.JLabel();
        jLabel3  = new javax.swing.JLabel();
        txtDestino  = new javax.swing.JTextField();
        jLabel4  = new javax.swing.JLabel();
        txtconductor  = new javax.swing.JTextField();
        jLabel5  = new javax.swing.JLabel();
        txtcliente  = new javax.swing.JTextField();
        jLabel6  = new javax.swing.JLabel();
        txtplaca  = new javax.swing.JTextField();
        jButton1  = new javax.swing.JButton();
        jButton2  = new javax.swing.JButton();
        jButton3  = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getContentPane()

        .setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText (
                

        "Viajes:");
        getContentPane()

        .add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane()

        .add(txtorigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        jLabel2.setText (
                

        "Lugar de Origen");
        getContentPane()

        .add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, -1));

        jLabel3.setText (
                

        "Lugar Destino:");
        getContentPane()

        .add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));
        getContentPane()

        .add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, 30));

        jLabel4.setText (
                

        "DPI: Conductor");
        getContentPane()

        .add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));
        getContentPane()

        .add(txtconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, 30));

        jLabel5.setText (
                

        "Dpi Cliente");
        getContentPane()

        .add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane()

        .add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        jLabel6.setText (
                

        "Placa de Vehiculo:");
        getContentPane()

        .add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));
        getContentPane()

        .add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 110, 30));

        jButton1.setText (
                

        "Registrar Viaje");
        jButton1.addActionListener ( new java.awt.event.ActionListener() {
            

        

        

        

        

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    }

    );
    getContentPane()

    .add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 170, 40));

    jButton2.setText (
            

    "Graficar");
    getContentPane()

    .add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 232, 110, 40));

    jButton3.setText (
            

    "Regresar");
    jButton3.addActionListener ( new java.awt.event.ActionListener() {
            

    

    

    

    

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
    }
}
);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 110, 40));

        pack();
    }// </editor-fold>                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Modulo.Principal.Principal ventana = new Modulo.Principal.Principal();
        ventana.show(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Vehiculo vehiculo1 = Registro.Vehiculo.getRegistro().search(new Vehiculo(txtplaca.getText(),"","",0,"","",""));
        Conductor Conductor1 = Registro.Conductor.getRegistro().search(new Conductor(txtconductor.getText(),"","","","","","",""));
        Cliente cliente1 = tabla.buscarCli(Integer.parseInt(txtcliente.getText()));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
>>>>>>> b1c7e65f098e099afc9d3892c5299beef4c1cb79

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuViaje









.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuViaje









.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuViaje









.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuViaje









.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
=======
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtconductor;
    private javax.swing.JTextField txtorigen;
    private javax.swing.JTextField txtplaca;
>>>>>>> b1c7e65f098e099afc9d3892c5299beef4c1cb79
    // End of variables declaration//GEN-END:variables
}
