/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo.Viaje;

import Entidad.Cliente;
import Entidad.Conductor;
import Entidad.Ruta;
import Entidad.Vehiculo;
import Entidad.Viaje;
import Estructura.TablaHash.TablaHash;
import Estructura.BlockChain.ListaSimpleB;
import Estructura.ListaSimple.ListaSimple;
import Modulo.Principal.Principal;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/**
 *
 * @author Co
 */
public class MenuViaje extends javax.swing.JFrame {

    
    ListaSimpleB blockchain = ListaSimpleB.getInstance();

    /**
     * Creates new form MenuViaje
     */
    public MenuViaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtorigen = new javax.swing.JTextField();
        txtdestino = new javax.swing.JTextField();
        txtconductor = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtminuto = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        txtmes = new javax.swing.JTextField();
        txtano = new javax.swing.JTextField();
        txthora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Viajes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("Lugar Origen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setText("Lugar Destino");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel4.setText("Dpi Conductor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel5.setText("Dpi Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setText("placa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));
        getContentPane().add(txtorigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        txtdestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdestinoActionPerformed(evt);
            }
        });
        getContentPane().add(txtdestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 80, 30));
        getContentPane().add(txtconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 120, 30));
        getContentPane().add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 40));
        getContentPane().add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 90, 30));

        jButton1.setText("Registrar Viaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 180, 60));

        jButton2.setText("Graficar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 170, 60));
        getContentPane().add(txtminuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 30, -1));
        getContentPane().add(txtdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 30, -1));
        getContentPane().add(txtmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 30, -1));
        getContentPane().add(txtano, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 30, -1));
        getContentPane().add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 30, -1));

        jLabel7.setText(":");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 20, 30));

        jLabel8.setText("Hora:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel9.setText("Fecha: DD/MM/YY");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel10.setText("/");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 50, 20));

        jLabel11.setText("/");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 20, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            Vehiculo vehiculo1 = Registro.Vehiculo.getRegistro().search(new Vehiculo(txtplaca.getText(), "", "", 0, "", "", ""));
            Conductor Conductor1 = Registro.Conductor.getRegistro().search(new Conductor(txtconductor.getText(), "", "", "", "", "", "", ""));
            Cliente cliente1 = TablaHash.getInstance().buscarCli(Integer.parseInt(txtcliente.getText()));
            String FechaHora = txtdia.getText() + txtmes.getText() + txtano.getText() + txthora.getText() + ":" + txtminuto.getText();
            String jave = txtplaca.getText() + FechaHora;
            Viaje viajesito = new Viaje(txtorigen.getText(), txtdestino.getText(), FechaHora, cliente1, Conductor1, vehiculo1, new ListaSimple<Ruta>());
            blockchain.agregarAlFinal(viajesito, jave);
            Registro.Ruta.getRegistro().rutaMasCorta(txtorigen.getText(), txtdestino.getText(), viajesito);
            JOptionPane.showMessageDialog(null, "Viaje creado con exito");
            vaciar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en crear el viaje");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void vaciar(){
        txtano.setText("");
        txtcliente.setText("");
        txtconductor.setText("");
        txtdestino.setText("");
        txtdia.setText("");
        txthora.setText("");
        txtmes.setText("");
        txtminuto.setText("");
        txtorigen.setText("");
        txtplaca.setText("");
    }
    
    private void txtdestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdestinoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String o =blockchain.grafica(blockchain);
        Entidad.Grafica.graficar(o, "Blockchain");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal ventana = new Principal();
        ventana.show(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtano;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtconductor;
    private javax.swing.JTextField txtdestino;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtminuto;
    private javax.swing.JTextField txtorigen;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
